### ISSUE TITLE
Issues with mathematical terminology

### ISSUE THREAD

**Issue by lewisje** [Pomax/BezierInfo-2#107]
Section 3 misleadingly claims that a function, properly defined, can only return a "single number"; in fact, a function can map values between any two sets, including vector spaces (and elements of finite-dimensional vector spaces are often realized as lists of elements of the underlying field, usually the real or complex numbers).

That is, an ordered pair of numbers is still considered to be a "single output" (often an element of a vector space of dimension 2 over the field in which the numbers exist).

---
Also, a polynomial with no term of degree 1 or higher is called a "constant" polynomial, and the term for degree 4 is "quartic" rather than "hypercubic" (the next few are based on Latin number-words, up to "decic" for degree 10 in common use); in section 4, you do have the right idea in not using a special term for a polynomial of degree 15 ("quindecic" is not in common use), but the word is "degree" rather than "order" (you may have confused this with the fact that the *order* of a *differential* equation is the highest number of derivatives taken of any factor in any term of the equation).

I noticed that in section 16, you do correctly use "quartic" for a polynomial of degree 4, and "quintic" for degree 5.

---
In section 12, the term for "the action of taking a derivative" is "differentiation" rather than "derivation"; I believe that what you meant to say about the nth derivative of a Bézier curve of degree n is that its graph is a point, and then any higher derivatives have the origin as their graph, but that difference doesn't matter much for graphics.

---
In section 16, the actual purpose of the second derivative is that if it is not zero where the first derivative is zero, then that point is a candidate for being a horizontal or vertical extremum; if it is zero at that point, you generally need to consider higher derivatives (if the first nonzero derivative is of even order, it's a local extremum; if of odd order, it's not, and if all derivatives are zero and yet the function is not constant, it's a strange case indeed) or start testing nearby points as a practical matter, if the first few derivatives are all zero. Also, it's important to treat points at which both the derivatives of x and of y are zero specially.

---
In section 20, it would be nice to note that C(t) is the coefficient of the cross product between the first and second derivatives of the vector function for the curve, considering that cross products were mentioned in section 14.

---
In section 21, "linear algerba" should be "linear algebra".

---
In section 32, it should be something like "corners" or "non-differentiable points"; a discontinuity would be a break in the graph, which means condition 1 isn't satisfied.

---
In section 33, the usual term for the exclusion region is the "symmetric difference".

---
Despite all that, the mathematics is solid.
---

**Comment by Pomax** [comment]
Only took forever, but all those excellent notes have been worked in, except for the "symmetric difference" as term for the exclusion, since this primer uses math to help those who need to program Bezier curves before anything else, and every graphics package I've ever worked with from vector graphics software to 3d modelling software calls this exclusion.

I've also left section 3 for now, mostly because this requires explaining that vector outputs "count" as single values, even though any kid looking at the formula would say "but that's more than one number". I'll have to think about an appropriate way to rephrase much of that section if I want to even mention vectors that early in the primer.
