### ISSUE TITLE
Typo "for ever" -> "for every"

### ISSUE THREAD

**Issue by lindig** [Pomax/BezierInfo-2#108]
> This can have drastic effects: **for ever** interval collapse, the curve order goes down, and curve continuity goes down, to the point where collapsing order knots creates a situation where all continuity is lost and the curve "kinks".

https://github.com/Pomax/BezierInfo-2/blob/fd1d7773cababda1a44cf757b5ec0eb9cdaf87ee/components/sections/bsplines/content.en-GB.md#L173

**Comment by Pomax** [comment]
Well spotted, although I would invite you to file a typo correct PR in the future: github lets you do this without ever leaving the browser, you can click the "edit" button for files on master (in this case https://github.com/Pomax/BezierInfo-2/blob/master/components/sections/bsplines/content.en-GB.md) and your edits will automatically be turned into a PR.

For now: fixed, thanks for letting me know!
