### ISSUE TITLE
Uncaught TypeError: Reordering.lower is not a function

### ISSUE THREAD

**Issue by mashabow** [Pomax/BezierInfo-2#119]
In section 11, pressing down arrow key doesn't lower the curve order. Here is a stack trace in the Chrome's console:

```
article.js:26239 Uncaught TypeError: Reordering.lower is not a function
    at _ (article.js:26239)
    at cl.onKeyDown (article.js:2008)
    at cl.onKeyDown (article.js:21860)
    at HTMLCanvasElement.eventProxy (article.js:39317)
```

**Comment by Pomax** [comment]
Hmm, that used to work just fine. Thanks for catching it, I'll have to look at what's going on when I have some time. Definitely marking as bug for now.

**Comment by Pomax** [comment]
fixed
