### ISSUE TITLE
Possible type in the "Manipulating curves" section?

### ISSUE THREAD

**Issue by alexjlockwood** [Pomax/BezierInfo-2#127]
I think there is a typo in the equation beginning with `A' = B' = ...`. I think the last part of that equation should use `B' - C`, not `B - C`?

I was also confused by this section a bit, because I wasn't sure how you defined the variables `e1` and `e2`. Are `e1` and `e2` vectors relative to `B`? Or are they expressed in absolute coordinates?

I also wasn't super sure what `v1` and `v2` were meant to represent.

<img width="1010" alt="screen shot 2018-03-18 at 7 49 09 pm" src="https://user-images.githubusercontent.com/1380747/37575715-dd01aeaa-2ae5-11e8-911d-2cc45a37a741.png">

**Comment by Pomax** [comment]
Yep, that's a typo, well spotted.

The `e1` and `e2` values are coordinates, I described them as `[...] endpoints e1 and e2 of the strut line relative to B' [...]` in the text  - if you interact with the graphic you will see those coordinates labeled:

![image](https://user-images.githubusercontent.com/177243/37609073-5e141992-2b59-11e8-9382-6f7f72836b1d.png)

The `v1` and `v2` values are also coordinates, representing the final intemediary points that we find in the linear skeleton of the cubic curve that we can use to compute the new control points. If you look at the graph, they are the points that connect directly to A' (they are unlabeled, but should easily spotted).

**Comment by alexjlockwood** [comment]
Ahh, I see. Got it. Thanks!

I see you submitted a fix for the typo, so will close this now. Thanks for the awesome writeup!

p.s. I managed to write this yesterday using your math: https://youtu.be/xIxa4ZlBQw8

And the code (if it looks familiar, it's because I stole some ideas from the `bezier.js` source :p): https://github.com/alexjlockwood/ShapeShifter/blob/309b7c5b220fbc01526014b30a86591650a01ea3/src/app/scripts/paper/gesture/focus/MouldCurveGesture.ts

**Comment by Pomax** [comment]
looks nice!
