### ISSUE TITLE
Thumbnail looks pretty ugly when I share your primer with other people :)

### ISSUE THREAD

**Issue by alexjlockwood** [Pomax/BezierInfo-2#128]
When I share a link to your primer on bezier curves, it looks like this:

<img width="1283" alt="screen shot 2018-03-18 at 8 21 44 pm" src="https://user-images.githubusercontent.com/1380747/37576518-171ce984-2aea-11e8-80f5-b53740635ad0.png">

Just thought I'd let you know... :)

**Comment by Pomax** [comment]
I don't know what to do with that information. It looks like wherever you're sharing pics the first image on the page, which is a very odd thing to do, especially at this point in the internet's life...

Where is this?

**Comment by alexjlockwood** [comment]
^ That is what it looked like when I shared a link to https://pomax.github.io/bezierinfo/ via Facebook Messenger.

I think there is a way to explicitly specify an image as a metadata tag or something... I think you're right that it simply picks the first image it can find on the page.

When I use this I see a warning saying that you should specify an `og:image` tag... maybe that's related: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fpomax.github.io%2Fbezierinfo%2F

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/43031374-6d10ed0a-8c55-11e8-8a0e-f19c6754d809.png)
