### ISSUE TITLE
Wrong condition in a binomial(n,k) function

### ISSUE THREAD

**Issue by s-w** [Pomax/BezierInfo-2#134]
There is a simple mistake in a for loop condition in the `binomial(n,k)` function:
```
binomial(n,k):
  while(n >= lut.length):
    s = lut.length
    nextRow = new array(size=s+1)
    nextRow[0] = 1
    for(i=1, prev=s-1; i<prev; i++):
      nextRow[i] = lut[prev][i-1] + lut[prev][i]
    nextRow[s] = 1
    lut.add(nextRow)
  return lut[n][k]
```
In the for loop there is `i<prev` and should be `i<=prev`.
With `i<prev` for `n=2` we'll have `s=2` and hence `prev=1` and `1<1`. So, for `n=2` there will be `[1, null, 1]` instead of `[1, 2, 1]`.

**Comment by Pomax** [comment]
Nice catch - want to turn that into a PR? (you can do that entirely in the browser by clicking through to the relevant file in the file tree, then clicking the edit icon for the file. Use the github IDE to fix the bug, and you can then file a PR with that fix without ever having to do any forking, cloning, desktop editor editing, git committing etc.)

**Comment by s-w** [comment]
I see you already updated GB version. I added PR for translations.

**Comment by Pomax** [comment]
Yeah, I was working on a new section for circle fitting and had to touch that code anyway, so I updated the original explanation for it too. 

Many thanks for the translations!
