### ISSUE TITLE
Pascal Triangle

### ISSUE THREAD

**Issue by zooid** [Pomax/BezierInfo-2#137]
In the first chapter you should give credit to Blaise Pascal, at least mention it's called Pascal Triangle or Pascal Pyramid

**Comment by Pomax** [comment]
You mean something like this?

>I say we could, because we're not going to: the factorial function is incredibly expensive. And, as we can see from the above explanation, we can actually create Pascal's triangle quite easily without it: [...]

It can do with a link to the wikipedia article on Pascal's triangle, so I'll update it with that, but it sounded a bit like you were admonishing me for not doing something I already did =)

**Comment by Pomax** [comment]
I've added the link, and also duplicated the mention to outside the implementation box.
