### ISSUE TITLE
Quadratic Curve / Line intersection special case

### ISSUE THREAD

**Issue by Ariyala** [Pomax/BezierInfo-2#155]
Hey,

I found an issue with the utils.roots() function for quadratic curves:

https://github.com/Pomax/bezierjs/blob/gh-pages/lib/utils.js#L396

if a, b and c are equally far apart (e.g. a = 50, b = 150, c = 250) then d becomes 0 and even though this is handled with that special case in line 396, this special case returns -2500 whereas it should return something like 0.55

You can even reproduce the issue in the Java live demo on the website:
![curve](https://user-images.githubusercontent.com/41535131/44970859-51b1b500-af08-11e8-9740-e484944f5821.png)

(it doesn't find an intersection point)

Any idea what's wrong here?

Cheers!
Ariyala

**Comment by Ariyala** [comment]
One solution I found is to do this for the special case:

return [1.0 - c / (c- a)].filter(reduce);

Not sure if this is the proper way to do it, but it works!

**Comment by Pomax** [comment]
thanks for filing! I'll have a look to see why this might be going so wrong O_o

**Comment by Pomax** [comment]
This looks like it got fixed a while back and this issue never got closed out.

![image](https://user-images.githubusercontent.com/177243/48648568-c1322f00-e9a4-11e8-9bc3-49f76dafff7a.png)

**Comment by Ariyala** [comment]
No, it's still broken :)

In your screenshot, move the middle point of the curve to Y = 150 and you will see ;)

**Comment by Pomax** [comment]
Ah, good correction. Reopening.

**Comment by Pomax** [comment]
Well, that was a delightful little bug. It was computing `(2*b-c) / 2 * (b-c)` rather than `(2*b-c)/(2 * (b-c))`.

**Comment by Pomax** [comment]
And all is well now.

![image](https://user-images.githubusercontent.com/177243/48664593-e9c63180-ea55-11e8-9a4e-1100da752829.png)
