### ISSUE TITLE
Signs inverted in section 18

### ISSUE THREAD

**Issue by simoncozens** [Pomax/BezierInfo-2#156]
In the third set of equations in s18 (After "If we then rotate the curve") we have:

 x = 0 (1-t)^3 ***+ 85*** • 3 • (1-t)^2 • t ***+ 12*** • 3 •(1-t) t^2 ...
 y = 0 (1-t)^3 ***+ 40*** • 3 * (1-t)^2 • t ***- 140*** • 3 • (1-t) t^2 ...

However, I think (and the example graphic "Aligning a cubic curve" shows) that the control points of the aligned curve should be ( ***-85*** , ***-39***) ( ***-12***, ***140***):

```JavaScript
>  n = new Bezier(120,160,35,200, 220,260,220,40)
> Bezier.getUtils().align(n.points,{p1: n.points[0], p2: n.points[3]})
[ { x: 0, y: 0 },
  { x: -85.14452515537582, y: -39.69143277919774 },
  { x: -12.803687993289572, y: 140.84056792618557 },
  { x: 156.2049935181331, y: -1.4210854715202004e-14 } ]
```

**Comment by Pomax** [comment]
good catch, thanks

**Comment by Pomax** [comment]
took a while, but: fixed, pushing an update soon.
