### ISSUE TITLE
Graph of coordinates vs. t: inaccurate range plotted

### ISSUE THREAD

**Issue by rMazeiks** [Pomax/BezierInfo-2#167]
In section 15: Component functions, the graphs are incorrectly plotting the x and y coordinates. When the actual coordinates are at 0, a negative value is plotted:

![image](https://user-images.githubusercontent.com/11248241/52165178-42bc7200-26f5-11e9-9b83-5cca6eb120d6.png)

**Comment by Pomax** [comment]
good find, let me see why that is.

**Comment by Pomax** [comment]
easy fix landed, "real" fix is _probably_ not worth adding in >_>
