### ISSUE TITLE
Chapter 32 wrong definition of 𝕋 matrix

### ISSUE THREAD

**Issue by kalo86** [Pomax/BezierInfo-2#172]
The 𝕋 matrix should be a square matrix.
The proposed definition of the 𝕋 matrix create elements on the column till the "n" (where "n" is the number of fitting point).
A generic  𝕋 matrix for a cubic Bezier curve passing through 4 points appears to be like the following:

𝕋 =       
| 1  s1  s1^2  s1^3  s1^4 |
| 1  s2  s2^2  s2^3  s2^4 |
| 1  s3  s3^2  s3^3  s3^4 |
| 1  s4  s4^2  s4^3  s4^4 |

The previous matrix is no more a square matrix.
Proposed solution: 𝕋 matrix should be defined till the "n-1" element in the column and till the "n" element in the row:

𝕋 =
| 1  s1  s1^2  s1^3 |
| 1  s2  s2^2  s2^3 |
| 1  s3  s3^2  s3^3 |
| 1  s4  s4^2  s4^3 |

**Comment by Pomax** [comment]
Thanks for filing - there was an email thread about this that never made it onto the repo as an issue.

**Comment by Pomax** [comment]
updated the chapter text and latex svg.
