### ISSUE TITLE
Chapter 32 typo in formula

### ISSUE THREAD

**Issue by kalo86** [Pomax/BezierInfo-2#173]
In the definition of the Cubic Bezier in parametric form, there is a missing coefficient:

![image](https://user-images.githubusercontent.com/48443579/55080891-2a3a5980-509f-11e9-9cc7-893554dd38c2.png)

Bcubic = a(1-t)^3+3bt(1-t)^2+**3**c(1-t)t^2+dt^3

**Comment by Pomax** [comment]
oh dang, good catch. fixed.
