### ISSUE TITLE
Dead link in section 37

### ISSUE THREAD

**Issue by PythagoRascal** [Pomax/BezierInfo-2#174]
The link for "work out the maths for how to do this" seems to be dead. Here I found an archived version of the link, not sure if it is the right one though.

Archive Link: https://web.archive.org/web/20140713004709/http://jazzros.blogspot.com/2011/03/projecting-point-on-bezier-curve.html

**Comment by Pomax** [comment]
always a shame when links go dead.... thanks for the heads up, I'll try to update it in the next few days!

**Comment by Pomax** [comment]
finally updated...
