### ISSUE TITLE
Bug in formula for section 11: Lowering and elevating curve order

### ISSUE THREAD

**Issue by ejpbruel** [Pomax/BezierInfo-2#19]
The formula to raise an n-th order curve to an n+1-th order curve contains a term i * w_(i - 1). i ranges from 0 to k (where k = n + 1), but w_(i - 1) is not defined for i = 0. Hence the formula is not well formed.

**Comment by Pomax** [comment]
indeed, let's fix that.

**Comment by Pomax** [comment]
Added a qualification for the `w_{-1}` case.
