### ISSUE TITLE
Error in section 12: Derivatives

### ISSUE THREAD

**Issue by ejpbruel** [Pomax/BezierInfo-2#20]
At the end of the section, it is stated that: "As such, a quadratic curve has no second derivative". That is not correct. A quadratic curve *does* have a second derivative (it *is*, however, constant, if that is what you meant). Wikipedia seems to get this right: https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Quadratic_B.C3.A9zier_curves

**Comment by Pomax** [comment]
That section is a series of statements, ending in "generalized: an nth order curve has n-1 (meaningful) derivatives", which is the part you should notice most. A constant zero-value derivative has no meaning.
