### ISSUE TITLE
Chapter 33 typo in formula

### ISSUE THREAD

**Issue by jatentaki** [Pomax/BezierInfo-2#210]
There is a typo in the first formula (definition) for `\mathbb{T}`: the penultimate column has `n-1` as its exponent, whereas it should have `n-2`. The second equation for `\mathbb{T}`, which follows immediately, has it correct.

**Comment by Pomax** [comment]
Oh, nicely spotted! On a small note (in case you happen across any other typos in the future), section numbers change as new sections get added (especially the later ones!) so the name of the section will be a more reliable indicator of where the problem is than the section number =)

**Comment by Pomax** [comment]
corrected
