### ISSUE TITLE
Tension parameter in Catmull-Rom

### ISSUE THREAD

**Issue by sidch** [Pomax/BezierInfo-2#213]
Hi Mike, thanks for a great resource. There's an inconsistency between your treatment of the tension parameter when you go from the control vector representation to the matrix+points representation in https://pomax.github.io/bezierinfo/#catmullconv (attached screenshot). Either the tension is in the denominator (former rep), so higher tension implies shorter tangents as in the text, or tension is in the numerator (latter rep), so lower tension implies shorter tangents. Could you fix this? The inconsistency is there at various places all the way to the end of that section.

![catmull_rom](https://user-images.githubusercontent.com/53786/64920482-d3a01380-d7d5-11e9-9fcd-0f1fcd006a98.png)

**Comment by Pomax** [comment]
oh wow, yes - well spotted, I'll try to get that fixed as soon as I get home later today.

**Comment by sidch** [comment]
Any updates?

**Comment by Pomax** [comment]
not yet, but thank you for the reminder. This got lost in a sea of deadlines.

**Comment by Pomax** [comment]
updated in https://github.com/Pomax/BezierInfo-2/commit/92f00778c5539b062291859aba9b5d275dbdae4c

**Comment by sidch** [comment]
Thanks!
