### ISSUE TITLE
Unexpected change of notation in ch 7 - Bézier curvatures as matrix operations

### ISSUE THREAD

**Issue by baryluk** [Pomax/BezierInfo-2#214]
At the start in the first equation, weights `w_i`, are replaced with different symbols, `P_i`, without a word or consistency with previous chapters. Same happens in codes, it was `w[]`, now is `points[]`. It is correct, but a bit confusing.

**Comment by Pomax** [comment]
Good point, I've filed https://github.com/Pomax/BezierInfo-2/issues/221 to fix that.
