### ISSUE TITLE
Undefined function and coefficients in ch 12 - Lowering and elevating curve order

### ISSUE THREAD

**Issue by baryluk** [Pomax/BezierInfo-2#215]
> We start by taking the standard Bézier function:
>
> `Bezier(n, t) = sum b_i B_i^n(t)`

Whoh. What is `b_i` coefficient and `B_i` polynomial?

This is even more confusing because in the same chapter we later use `B_k` to represent matrices, not functions.

**Comment by baryluk** [comment]
Hmm. Maybe these `B_i^n(t)` are Bernstein basis polynomials of degree n?

**Comment by Pomax** [comment]
Good observation, I've filed https://github.com/Pomax/BezierInfo-2/issues/220 to address it.
