### ISSUE TITLE
Non-standard notation for derivatives - ch 13

### ISSUE THREAD

**Issue by baryluk** [Pomax/BezierInfo-2#217]
I have never seen a derivative of a function be represented by `d/dt` on the right side of the function. In fact putting `d/dt` on the right makes it look like a function operator or functional, which is not the case here.

It should be on the left.

**Comment by Pomax** [comment]
Then you will need to read that expression again, because the right side is simply the expanded form of the left side. The `d/dt` is there because nothing has been resolved yet.
