### ISSUE TITLE
Suggestion - ch 4.5 - Bezier curves in 2 dimensions

### ISSUE THREAD

**Issue by baryluk** [Pomax/BezierInfo-2#218]
Actually text doesn't mention that weights and points can and are usually vectors (i.e. in 2-d space).

Just applying blindly all the functions and formulas will give you a constant function `1` or a line on 1-d line. Not very useful at all and well confusing.

**Comment by Pomax** [comment]
I'm not sure I understand your suggestion: each dimension in a multidimensional Bezier curve is evaluated independently. It has its own weights, and yields its own value. Whether you use vectors or not makes no difference to the _actual_ calculations that happe: the full-dimensional coordinate is still simply the set of however many dimensions you evaluated separately.

**Comment by baryluk** [comment]
My point is that the tutorial doesn't mention this anywhere really, at least not early on. It doesn't make sense to do Bezier curves in 1d per-se, because well it would be just a flat segment, no matter the weights and control points.

**Comment by Pomax** [comment]
I don't understand why you would say that, when the entire text leading up to that point covers the fact that we're building a function that yields more than one value, by evaluating separate functions for each dimension. We don't need to use the word "vector" to explain that you need two values if you want an (x,y) coordinate, that can come when we talk about matrices (which is a topic a surprisingly high number of people will _not_ be familiar with)
