### ISSUE TITLE
explain finding bezier inflections

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#22]
explain how to find where a bezier curve inflects, as the only explanation right now is about the component functions.

**Comment by Pomax** [comment]
http://stackoverflow.com/questions/35901079/calculating-the-inflection-point-of-a-cubic-bezier-curve/35927917#35927917

**Comment by Pomax** [comment]
added

**Comment by FrostedPenguin** [comment]
Found typo in https://pomax.github.io/bezierinfo/#inflections.
A formulation in below the sentence 
> Aligning our curve so that three of the eight coefficients become zero, we end up with the following simple term function for C(t):


should be C(t) = 18 * ((-3a + 2b + 3c - d)t^2 + (3a - b - 3c)t + (c - a))



not C(t) = 18 * ((3a + 2b + 3c - d)t^2 + (3a - b - 3c)t + (c - a))



Also currently I'm writing my own bezier curve codes. But this reduced form of curvature doesn't give me right numerical value. It usually smaller than the real value of curvature.

**Comment by Pomax** [comment]
Could I ask you to please file this as a new issue, as it is not related to the task of adding the section itself, but is a new issue around that content after it was added to the site?
