### ISSUE TITLE
Arc to Cubic bezier issue

### ISSUE THREAD

**Issue by PixelSir** [Pomax/BezierInfo-2#253]
After implementing the math, it seems this only works under the assumption that the arc is flat and not helical where the arc increases or decreases in height. 

If you have an arc that starts at some height and ends at a different height, such as a helix, the resulting control points are no longer correct.

Do you know how to factor in the slope of a helix at the tangent point for the two control points? I have been stuck trying to work it out.

**Comment by Pomax** [comment]
Do you have the code for that helical arc? As long as the arc is planar, things should work. If they're not... things get _a lot_ more complicated.

**Comment by Pomax** [comment]
closing as "probably not actually an arc" - it might be interesting to work out how to approximate helixes using Bezier curves, but that'd have to be a separate section with a separate issue filed to address it.

**Comment by PixelSir** [comment]
Sorry, i have been simply too busy to reply lifes been abnormally crazy the last few months, when i get time in future i will post again with my progress on helix's!

**Comment by Pomax** [comment]
much appreciated!
