### ISSUE TITLE
Primer Diagrams Not Working in Safari

### ISSUE THREAD

**Issue by ermader** [Pomax/BezierInfo-2#271]
Today I opened the primer in Safari and all of the diagrams have a header that says "Scripts are disabled. Showing fallback image." If I open the JavaScript console I get the error message `[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.` (Sorry, I don't know how to track this down to a particular line of code.)

This happens in Safari 13.1.2 and Safari Technology Preview 14.0.1 on macOS Catalina 10.15.6, and Safari on iOS 14.0. The primer behaves as expected on Firefox 81.0.

**Comment by Pomax** [comment]
No need to apologise: Safari has been the new IE for a few years now. You'd think the people who _make_ Safari need stack traces for errors, but apparently the people that make Safari don't use Safari (and I guess that makes sense, I'd rather use Chrome or Firefox or even Edge or Opera, too).

So: can confirm, this might be related to static property assignment - if it is, that's not too much work to fix. If it's not, this may very well end up being one of those "unless someone wants to pay me for the time, I am not sinking hours into debugging this for a browser that only offers "no other choice" on iPhone/iPad".

**Comment by Pomax** [comment]
Marking as "help wanted" just in case someone happens to be interested in looking at this because it's a problem they've encountered before, too.

**Comment by Pomax** [comment]
Far as I can tell that was the problem - thankfully only used in two places so easy enough to fix.
