### ISSUE TITLE
buy Pomax a coffee page invalid

### ISSUE THREAD

**Issue by aerofidelity** [Pomax/BezierInfo-2#273]
1.  When I click on the link to the buy Pomax a coffee page, it claims that my session is invalid or expired, even though I am currently logged into PayPal.  I created a PayPal account just for this purpose, so maybe there is something wrong on my end.

![Capture](https://user-images.githubusercontent.com/67231576/94350179-9d0ff200-0000-11eb-9b03-c1f7d64a1ca8.PNG)

**Comment by Pomax** [comment]
Neat, let's see if I can ask paypal to give me the proper URL... thanks for letting me know.

**Comment by Pomax** [comment]
Link updated, the format's definitely changed, so now it's a few preset amounts and a freeform field.
