### ISSUE TITLE
Question about section 30 "The project identity"

### ISSUE THREAD

**Issue by canhnht** [Pomax/BezierInfo-2#276]
Hi, thanks a lot for building this book.
In section 30 "The project identity" of this version https://pomax.github.io/bezierinfo/#abc, I don't quite understand this sentence:

> For cubic curves, there is no single pair of points that can act as e1 and e2

As I understand, this part is about reverse engineering of de Casteljau algorithm. For cubic curve, could you help to explain a little bit how to find e1 and e2 points from A point?
Thanks in advance.

**Comment by Pomax** [comment]
There is no "finding", you have to "decide" what they are: they have to follow the de Casteljau rule  in that `e1` and `e2` *must* lie on the line between `v1` and `v2` and that they follow the `t` ratio, so the distance from `B` to `e1` and the distance from `B` to `e2` must have a ratio of `t:(1-t)` like everything else. However, _how far from B_ you place `e1` (which then fully constrains `e2`) is up to you.
