### ISSUE TITLE
Molding a curve

### ISSUE THREAD

**Issue by canhnht** [Pomax/BezierInfo-2#278]
I'm following implementation of section Molding a curve https://pomax.github.io/bezierinfo/#molding to implement feature molding a curve similar to Adobe Illustrator.
But it seems that Illustrator's way of adjusting curve's shape is quite different from 2 ways mentioned in this section.
Is it due to the difference in calculating e1 and e2 points?
Is there anyway to adjust the calculation to implement similar molding curve like Adobe Illustrator?
Thanks in advance.

**Comment by Pomax** [comment]
Yes, as the choice in `e1` is entirely free, and there are many curve aspects that you can use to decide how far to place it from the point you're dragging, the difference in what the Primer shows, and what Adobe Illustrator does, is just the choice in `e1`.  One things that AI does is choose an `e1` so that at any moment while you're dragging the point perpendicularly across the baseline, that all the control points move along a parallel trajectory.

**Comment by canhnht** [comment]
@Pomax, thanks a lot for explaining AI's way.
I think the AI's way will directly calculate the position of control points and there's no need to calculate `e1` or `e2` points.
Since the control points move along the parallel trajectory, they can simply be calculated based on the movement vector of the point on curve.
Do I understand correctly?

**Comment by Pomax** [comment]
They do a little bit more (they move proportionally, corrected such that the cursor point stays an on-curve point). I'm actually going to file a new implementation issue to see if there is a way to describe how it does it without violating any Adobe copyrights.

**Comment by canhnht** [comment]
@Pomax I also implemented the curve molding such that the control points will move proportionally, which means in some cases, one control point will move a little bit faster that the other control point.

About violating Adobe copyrights, do you mean copying the mechanism of molding curve of Pen Tool in Adobe could violate copyrights, although I implemented it by myself?
I'm quite curious for these copyrights things.
Hope you can help clarify it a little bit.
Thanks a lot.

**Comment by Pomax** [comment]
while it is hard to copyright "maths", you can copyright specific things, so if AI is the only one to mold curve in this _specific_ way and you reverse engineer it exactly, that _might_ be a violation (not that I expect it to be, but in the world of courts, ignorance is not a defense, so if you don't _know_ it's fine, you assume it's not fine and you find out first).

**Comment by canhnht** [comment]
@Pomax, thanks for your reply.
I think the term "reverse engineer" is used in case that you decompile the program and copy its source code. But for my case, I'm just mimicking its functionality. I implemented whole code by myself, from scratch, so I'm just afraid if mimicking their idea of building Bezier curve will be a violation. 🙄 I will find out more about this.

**Comment by canhnht** [comment]
There is also another site called figma.com that has similar mechanism of molding curve like Adobe Photoshop.
I also found this patent from Adobe https://patentscope.wipo.int/search/en/detail.jsf?docId=US226139787 which is probably patent for mechanism of Pen Tool, so my intention of mimic Pen Tool in Illustrator could be a violation. 😓

**Comment by Pomax** [comment]
I'm not saying _that_ there are any legal issues, just that if you're trying to implement the same behaviour, by copying what you see happening in a program, then depending on the country you live in you, as a business intending to use that in your own commercial product, have a legal duty to verify that you're not infringing on anyone's rights.

I'd be _highly_ surprised if anyone bothered to try to claim that curve fitting (which curve molding is, of course) is somehow (a) programming and (b) something that they uniquely have the right to own, but let's be clear: the US has a highly ineffective system when it comes to deciding whether something can be "owned" or not, and rewards legal ownership to things that no sane person with a little knowledge of the field involved would ever agree should be claimable.

**Comment by canhnht** [comment]
Thanks a lot for the reply!
I will definitely verify the copyrights infringement for this patent.
As there is already a patent for the methods of creating and editing arcs, I think I would be careful in building my Pen Tool to not violate the protections specified in patent, but at the same time can produce a good Pen Tool for users.

Previously, I have mentioned site Figma with similar pen tool. But from their blog, they created a tool for creating and editing arcs called Vector Networks in 2016. https://www.figma.com/blog/introducing-vector-networks/, while the patent is published in 2019, so I think the Figma's pen tool, although has similar methods of creating and editing arcs, but will be fine.

Sorry for bothering you so long in these patent things 😓 🙇‍♂️
These patent things are hard to understand correctly. I will research more about it. I hope that a good Pen Tool on the web could be produced without any violation. 🙇‍♂️

**Comment by Pomax** [comment]
note that the patent you link to is a continuation of the a previous patent, so you'll probably have to go back in time a bit further.

**Comment by canhnht** [comment]
Yeah, you're right. From this website https://patents.justia.com/search?q=TOOL+FOR+CREATING+AND+EDITING+ARCS, there are total 3 patents. The oldest date of these 3 patents is August 25, 2016. Figma's tool is dated back in February, 2016. So I think it's totally fine for Figma.

**Comment by Pomax** [comment]
and note that Inkscape's been around for a _long_ time, as have several other vector drawing tools. Figma's only a very recent app to get released.

**Comment by canhnht** [comment]
Oh, thanks a lot for the info!
Inkscape also implemented a tool for creating and editing curves similarly to the methods described in patent, but implementation details such as the way of molding curve is a little bit different.
Inkscape is also free and open source, then I think it's better to follow Inkscape's pen tool.

**Comment by canhnht** [comment]
It turns out that there are many free online and desktop vector graphics editor (e.g. Youidraw, Vectr) and tool for creating and editing curves are a necessary feature in vector graphics editor. A similar mechanism described in Adobe's patent is also implemented in these editors.
I start to get confused by the importance of this patent. I guess I can follow features of these free editors, instead of mimicking too much from Adobe Illustrator.
