### ISSUE TITLE
Number of curve-curve intersections is wrong.

### ISSUE THREAD

**Issue by JezuzStardust** [Pomax/BezierInfo-2#281]
In paragraph 29, the testing windows get the number of intersections wrong quite often. My guess is that this is the so-called "clusters" you talk about. Experimenting a bit, the number of intersections is not changed by changing the threshold. This seems to happen when one of the curve happens to be split very close to the intersection. 

Thank you for this fantastic source!

**Comment by Pomax** [comment]
yeah: as long as the number is "too high", that's expected. If it's too low, that's a bug.
