### ISSUE TITLE
arc length: make explicit what `f(t)` is

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#31]
right now it's left to the reader, who might not be able to guess correctly

**Comment by garciadelcastillo** [comment]
I am actually having a hard time with this one right now!

While the concept of a generic f(t) function for a Bezier curve is clear (e.g. for a cubic one):

    f(t) = (1-t)^3 + 3 * t * (1 - t)^2 + 3 * t^2 * (1 - t) + t^3;

when applying weights to compute points along a particular curve, we obtain two parametric equations for x and y, in the form:

    Bx(t) = x1 * (1-t)^3 + x2 * 3 * t * (1 - t)^2 + x3 * 3 * t^2 * (1 - t) + x4 * t^3;
    By(t) = y1 * (1-t)^3 + y2 * 3 * t * (1 - t)^2 + y3 * 3 * t^2 * (1 - t) + y4 * t^3;

It is unclear which/how to use them when solving the approximate integral for arc length calculation. 

I also have another suggestion for contributing to the document. I'd be happy to pull them along this extended explanation. 

Btw, AMAZING primer, thank you so much! ;)

**Comment by Pomax** [comment]
The `f(t)` is the equation we're trying to compute the integral of (the square root, of the sum, of the squares of x and y each, `sqrt(x(t)^2 + y(t)^2`).

**Comment by Pomax** [comment]
updated the function with one more step to hopefully make this clear.
