### ISSUE TITLE
Incorrect matrix representation in the curve fitting section

### ISSUE THREAD

**Issue by FreyaHolmer** [Pomax/BezierInfo-2#313]
Hey!
It seems like the matrix representation here isn't entirely correct, I think!

![image](https://user-images.githubusercontent.com/3438510/124612174-69f16d80-de72-11eb-8b4d-2373a4833735.png)

the first one results in a row matrix (marked red), while the second part results in a scalar (marked green). I presume the scalar is the intended value?

summing each row in the matrix in the left equation (marked blue) would make it output a scalar as well

(also, love your writeup in general, it's wonderful!)

**Comment by Pomax** [comment]
Yep, spot on: there should definitely be some plus signs in there, thanks for letting me know =D

(and thank you for the kind words, always happy to hear from folks finding value in the primer!)

**Comment by Pomax** [comment]
updated and pushed, thanks again for reporting.

![image](https://user-images.githubusercontent.com/177243/125203541-9bc95200-e22d-11eb-9b5d-bdcd8e80bf64.png)
