### ISSUE TITLE
"Mouse over" instruction in section 8 seems incorrect

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#315]
In [section 8](https://pomax.github.io/bezierinfo/#decasteljau) it's written:

>To see this in action, **mouse-over** the following sketch. **Moving the mouse** changes which curve point is explicitly evaluated using de Casteljau's algorithm, **moving the cursor** left-to-right (or, of course, right-to-left), shows you how a curve is generated using this approach.

(bold mine).

I can see it all by moving the slider, NOT by mouse over. Am I missing something?

**Comment by Pomax** [comment]
No, that text got missed during the last huge rewrite that made things more accessible for touch-devices, but that text apparently got missed. Thanks for spotting it.

**Comment by Pomax** [comment]
updated in https://github.com/Pomax/BezierInfo-2/commit/5a285c603d49a8327dc6e2aa95507118a525cb43
