### ISSUE TITLE
Projection identity: why C lies always at the same % from start and end points?

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#316]
From [section 30](https://pomax.github.io/bezierinfo/#abc) "The projection identity":

> for any point on the curve with some t value, the ratio of distances from A to B and B to C is fixed: if some t value sets up a C that is 20% away from the start and 80% away from the end, then it doesn't matter where the start, end, or control points are; for that t value, C will always lie at 20% from the start and 80% from the end point.

Pomax, I don't understand **why "(A - B) / (B - C) fixed" imply "(C - start point) / (C - end point) fixed"**.

From the sketch, by moving the points around I see (A - B) / (B - C) is always the same number, but when I move the start or end point, C also moves, and I am not sure C lies always at the same % from start or end point. am I missing something obvious? Thanks :)

**Comment by Pomax** [comment]
C moves, the physical distances between start point and C, and C and the end point change, but the _ratios_ between those distances do not, and you can verify this by taking a curve you're not sure about, and then just "running the numbers" with a pen an paper (and calculator =D) to confirm that the distance ration for C stays exactly the same.

**Comment by luc4leone** [comment]
Thanks! 💯
