### ISSUE TITLE
Document navigation

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#317]
hey Pomax,

I am jumping back and forth between sections a lot. This is definitely not a novel that one reads from start to finish. I have a MAC and I do a lot of cmd+up to go to the table of content, then I click on the section link. The problem with cmd+up is that it doesn't bring me _exactly_ to the table of content. I have to press the spacebar. NOT a big issue of course.

A quick "fix" would be to add an [index](url) link close to the [previous](url) [next](url) that on click would bring the user to the table of content.

![image](https://user-images.githubusercontent.com/2797254/130939939-a48336a8-23c6-4624-b83c-c20b960c4cd0.png)

A _much better_ "fix" would be to add a left sidebar, where one could see the table of content and immediately click on the relevant section link to jump there.

just my 2 cents 😉

**Comment by luc4leone** [comment]
I guess the equivalent shortcut on Windows is Ctrl+Home. Of course one can scroll with the mouse instead of jumping with the keyboard shortcut to the top of the file. My point is just that, from my experience these last days, having the table of content "at hand" would make the navigation / studying of the Primer easier 👍

**Comment by Pomax** [comment]
I've added toc links between "previous" and "next", the fact that the toc is not a persistent nav, or at the top of the page, is not a usability concern.

**Comment by luc4leone** [comment]
>I've added toc links between "previous" and "next"

nice page navigation improvement according to me 💯
