### ISSUE TITLE
What's the `curve` parameter in `flattenCurve`?

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#318]
In [section 9](https://pomax.github.io/bezierinfo/#flattening), in pseudo-code you define `flattenCurve`. What's its `curve` parameter? It seems to be the list of the bezier curve points. If my guess is correct, where's it coming from? It can't be the output of `drawCurve`, since that function just draw a point of the curve.

I am asking because if `curve` is the whole list of bezier points, and it's a given, I am confused: wasn't the goal of the sections 8 and 9 to calculate that list, full or flattened?

PS: I got it that if I call `drawCurve` 200 times for 200 different t in [0,1] I get 200 points of the curve, that I can flatten to, say 100, then draw 99 lines and still get a beautiful curve. Is that what you had in mind?

**Comment by luc4leone** [comment]
>It's literally "the API for a curve"

clear now, thanks Pomax, I didn't get it before. I went to read https://pomax.github.io/bezierjs/ and I think this is a curve:

`cost curve = new Bezier(control_points)`

Now I think I get the steps clear:

1. I create a Bezier object 👉 `curve`
2. I get a subset of the curve points (I got it by calling the`compute` method) 👉 `flattenCurve`
3. I draw the curve by drawing lines between the points of the subset 👉 `drawFlattenedCurve`

**Comment by Pomax** [comment]
correct. But note that the Primer never gives you "actual code", it gives you conceptual code. It doesn't talk about "the `curve` Object used by bezier.js", it takes about "some object called `curve` that has the functions that we need to call, as used in this demonstrator code".

**Comment by luc4leone** [comment]
right, up to the reader to write the actual code. I am translating the psedocode into javascript. Actually I couldn't see any way I could create by myself a `curve` object that would allow me to then write the following `flattenCurve` and `drawFlattenedCurve`. 

Actually this is a point I'd like to ask your advice. What if I knew ruby but not javascript: how could I have created the Bezier class, that would give me the `curve` object to then being able to follow the tutorial and traslate the pseudo code into ruby?

**Comment by Pomax** [comment]
No idea, I never looked at ruby.

**Comment by luc4leone** [comment]
I think my question was badly written. What I meant was:

1) In section 9 I'd like to traslate the psudocode you provide for `flattenCurve` and `drawFlattenedCurve`... let's say in ruby
2) To do that, I need a `curve` object, that has some methods that allow me to call `getX(t)` and `getY(t)`

Do I have the necessary info in the previous sections, from 1 to 8, to write that class by myself?

**Comment by Pomax** [comment]
as long as you know how to write classes, then yes.

**Comment by luc4leone** [comment]
Perfect! That was not so obvious to me, but I had the suspect that it was possible 😄 
I guess I have to pay more attention to those sections (1-8), I'd like to create a `Bezier` class by myself – maybe a simpler one – instead of "stealing" yours 😉
