### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by yay** [Pomax/BezierInfo-2#32]
A and B are never defined, yet you refer to them in the text.
Do you mean S and E instead?

<img width="818" alt="screen shot 2016-07-01 at 21 19 52" src="https://cloud.githubusercontent.com/assets/1799756/16532322/9bc072a6-3fd1-11e6-8edf-5dfe9810ec70.png">

**Comment by Pomax** [comment]
sorry for the late reply, github never notified me of a lot of messages on various repos... yeah that should be S and E, I'll try to fix that asap.

**Comment by yay** [comment]
No problem. BTW, thanks for a great guide. It's a real gem.

**Comment by Pomax** [comment]
fixed by https://github.com/Pomax/BezierInfo-2/commit/19bb1e1f2ec911fe348a6b9a3250a03435090cbc
