### ISSUE TITLE
Update `drawCurve` name in section 10

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#320]
@Pomax, since you updated `drawCurve` in section 8, to be consistent, you might want to also update `drawCurve` in section 10.

**Comment by Pomax** [comment]
Good note - updated in https://github.com/Pomax/BezierInfo-2/commit/0bc057e81150600abb00df1407f5c0cdd3ce26bc, including the ones that were missed in the translated content.
