### ISSUE TITLE
Wrong graphics caption in section 31

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#321]
In the last graphics of section 31, the caption is "Fitting a quadratic Bézier curve". Shouldn't it be "Fitting a _**cubic**_ Bézier curve"?

**Comment by Pomax** [comment]
it very much should. Updated in https://github.com/Pomax/BezierInfo-2/commit/fdc8adfe50ff79b39e9ab166ef8aa51af5b200bd
