### ISSUE TITLE
#abc section: cubic curve construction requires start, end, t, and some point B, not just start, end, and t.

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#322]
At the end of [section 30](https://pomax.github.io/bezierinfo/#abc) it's written:

>So: if we have a curve's start and end points, then for any t value we implicitly know all the ABC values, which

Don't we need `start`, `end`, `t` **and** `B`? From `start`, `end` and `t` we can calculate `C`, but then we need also `B` to find `A` from the ratio equality, don't we? By the way, that's also what's written a few lines above:

>given three points (start, end, and "some point on the curve"), as well as a t value, we can construct curves.

**Comment by Pomax** [comment]
No, because `B` is the on-curve point for `t`.

**Comment by luc4leone** [comment]
>Having the curve's control points and a t value gives us B (by evaluating the curve at t)

by "control points" you mean all the four points? I understood we only have two of them, `start` and `end`, making it impossible to calculate the curve. Actually isn't the whole "procedure" done to calculate the other two control points:

![image](https://user-images.githubusercontent.com/2797254/131362541-aa3b80d6-7bcf-4180-b58f-3fa4d7c4ced8.png)

**Comment by Pomax** [comment]
all points are control points (they all control the curve), for a cubic curve, two of those are "just control points", and two are "on-curve" points as well (namely, the start and end point), so the convention is that C1 is the "first pure control point" and C2 is the "second pure control point".

As for the fact that we don't have all the points: I see what you mean,

**Comment by luc4leone** [comment]
Great, thanks for the explanation Pomax!

**Comment by Pomax** [comment]
updated in https://github.com/Pomax/BezierInfo-2/commit/8650571c7095d66bfb7b53ce21bc0d6dd7ff7403
