### ISSUE TITLE
How do we derive control points from `start`, `end`, `B` and `t`

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#323]
In [section 30](https://pomax.github.io/bezierinfo/#abc)

>For cubic curves, there is no single pair of points that can act as e1 and e2: as long as the distance ratio between e1 to B and B to e2 is the Bézier ratio (1-t):t, we can reverse engineer v1 and v2

@Pomax the above is not clear to me and I feel it's crucial to understand, can you please elaborate it further?

Also:

<img src="https://user-images.githubusercontent.com/2797254/131347092-d48f4536-cc0d-4a25-b2a5-1d9d7d1ba87a.png" width="660" />

**Comment by Pomax** [comment]
The first set looks like it uses notation that matched a previous graphic, those primes shouldn't be there. As for the second function, what part is not clear? Those are the v1 and v2 values that we computed two lines up, and is further explained by looking at the graphic again, which explains what e1/e2 and v1/v2 are.

![image](https://user-images.githubusercontent.com/177243/131359381-5adf9595-f9ee-408c-8422-4078d369597f.png)

**Comment by luc4leone** [comment]
Hey @Pomax, first of all thanks. A couple of questions.

### first question

If 

`e1 = (1-t)*v1 + t*A`

I get calculate v1 in a couple of steps:

`e1 - t*A = (1-t)*v1`

then

`e1 - t*A / 1-t = v1`

which is different from

![image](https://user-images.githubusercontent.com/2797254/131390046-ccc05848-63ef-4035-ad61-eaab49bbdc13.png)

where's my mistake?

### second question

 >For cubic curves, there is no single pair of points that can act as e1 and e2

what do you mean exactly?

**Comment by Pomax** [comment]
1) that's a good point, it looks like that formula for v1/v2 isn't correct, and should be updated.
2) note that the text doesn't say "there is no pair of points", but "there is no _single_ pair of points". There are infinitely many pairs of e1 and e2 that we could use, each yielding a different final curve, based on the fact that the tangent at B is not fixed for cubic curves (unlike for quadratic curves), so it's up to us as designers/implementers to pick what seems a reasonable pair with which to perform the curve construction.

**Comment by luc4leone** [comment]
>then that becomes `(e1 - t*A) / (1-t) = v1`, not `e1 - t*A / (1-t) = v1`

absolutely, I missed the parenthesis, but yeah, what you wrote is what was on my mind, my bad!
