### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#324]
[Section 31](https://pomax.github.io/bezierinfo/#pointcurves)

>That means that if we have have three points on a circle

one "have" too many 😉

**Comment by Pomax** [comment]
Please use the edit function on github to fix typos via PR.

![image](https://user-images.githubusercontent.com/177243/131548083-58e3d36b-eb90-45e5-8924-0de9051f6103.png)

**Comment by luc4leone** [comment]
ok, I will 👍
