### ISSUE TITLE
Error in "Deriving new hull coordinates"

### ISSUE THREAD

**Issue by behdad** [Pomax/BezierInfo-2#33]
This text (and the matrix just before it):

```
Brilliant: if we want a subcurve from t = 0to t = z, we can keep the first coordinate the same (which makes sense), our control point becomes a z-ratio mixture of the original control point and the start point, and the new end point is a mixture that looks oddly similar to a bernstein polynomial of degree two, except it uses (z-1) rather than (1-z)... These new coordinates are actually really easy to compute directly!
```

I think this sentence: "except it uses (z-1) rather than (1-z)" is misleading.  If you replace (z-1) with -(1-z) you get the bernstein polynomial (note the second term is negative already, which cancels out).  Indeed, the endpoint of the first split half is the curve point at t=z, so it must be the same.

**Comment by Pomax** [comment]
Only about 2 years late, but: took that note out. -(z-1) is trivially the same as (1-z) so that, indeed, made no sense.
