### ISSUE TITLE
An interval division is incorrect in a sample code for projecting a point

### ISSUE THREAD

**Issue by emaame** [Pomax/BezierInfo-2#347]
I believe at an interval should be divided by 4 (not 5) at [refine-binary.js:22](https://github.com/Pomax/BezierInfo-2/blob/bc1bffb8e6af05877b1e7d36cc57643de0fc6b5a/docs/chapters/projections/refine-binary.js#L22), for binary search.

An interval with 5 points: [`t1`, `n1`, `n2`, `n3`, `t2`] , then `n1` should be `t1 + (t2 - t1) / 4`.

It is used from a sample code for [Projecting a point onto a Bézier curve](https://pomax.github.io/bezierinfo/index.html#projections).
Another algorithm is used in `Besier.project` of `besier-js` so that this problem does not effect to `besier-js` (it use a simple linear search).

thank you for your works.

**Comment by Pomax** [comment]
good catch, thanks for letting me know!

**Comment by Pomax** [comment]
fixed in https://github.com/Pomax/BezierInfo-2/commit/c683fa699b838d8c2e8e07c7b7d5dacd3fe093e3
