### ISSUE TITLE
Cusp is generally not considered a self-intersection

### ISSUE THREAD

**Issue by deanm** [Pomax/BezierInfo-2#36]
Currently written: "anywhere on and in the red zone, the curve will be self-intersecting, yielding either a cusp or a loop. "

However, I believe it is not proper to call a cusp point a self intersection. "A Geometric Characterization of Parametric Cubic Curves" words it as:

"A curve with a loop is self-intersecting, one with a cusp has a point where the unit tangent vector is discontinuous ..."

**Comment by Pomax** [comment]
finally fixed. That only took over 2 years to get to.
