### ISSUE TITLE
Section 3 "times one" ambiguous ?

### ISSUE THREAD

**Issue by lucky101man** [Pomax/BezierInfo-2#37]
In section 3:

> I know what you're thinking: that doesn't look too simple, but if we remove t and add in "times one", things suddenly look pretty easy. Check out these binomial terms:

Could you say:
 "... but if we replace the _t_ and _(1-t)_ terms with "times one".... "
or 
"... or if we remove the terms involving t and add..."

I was confused by this for a while because I was mentally replacing the t in (1-t) term with a "times one" and getting (1-1) - 0. I didn't figure out that your were replacing the (1-t) term as a whole until I got to the function example at the end of the section where you use t,t2,t3,mt,mt2,mt3 then it became clear.

Of course it's all so obvious now :)

**Comment by Pomax** [comment]
but that's not what I do, I literally mean exactly what those words imply: turning any `term` into `term x 1`.

**Comment by atskae** [comment]
Wow, I totally had the exact same confusion... I'm glad I wasn't the only one!
