### ISSUE TITLE
Stop build at ??

### ISSUE THREAD

**Issue by borneq** [Pomax/BezierInfo-2#386]
file:///home/andrzej/wazne/gitmy/BezierInfo-2work/docs/js/graphics-element/api/graphics-api.js:689
    let w = this.panelWidth ?? this.width;

file:///home/andrzej/wazne/gitmy/BezierInfo-2work/docs/js/graphics-element/api/types/matrix.js:130
    this.data = data ?? [...new Array(n)].map((v) => [...new Array(m)].map((v) => 0));
        
file:///home/andrzej/wazne/gitmy/BezierInfo-2work/docs/js/graphics-element/api/impart-slider-logic.js:120
        let checked = transform ? transform(value) ?? value : value;

steps to reproduce : npm test
remove ?? code and "npm test" again

**Comment by Pomax** [comment]
Stop using Node 15 or older.
