### ISSUE TITLE
Incorrect mathematical assertion in "Finding Y, given X"

### ISSUE THREAD

**Issue by Pixneb** [Pomax/BezierInfo-2#394]
First of all, thank you for this incredible resource!

I am implementing a version of the algorithm described in "Finding Y, given X".  It says:

> let's just run cubic root finding - and not even the complicated cubic case either: because of the kind of curve we're starting with, we know there is only root, simplifying the code we need!

I don't think this is necessarily true.  It is true that there is only one root with t in [0, 1], but there may be other roots that are outside [0, 1] that we must find and then reject.  I eagerly accepted the apparent invitation to implement only the `discriminant > 0` case of Cardano, and quickly found cases that tripped my assertion.  I can find one on this site if you need!

If I'm not mistaken, then the fix is just to delete the "not even the complicated case" phrase.  But of course I could easily be mistaken!

**Comment by Pomax** [comment]
Rather than deleting the phrase, I'll rewrite it to:

> let's just run cubic root finding - and not even the complicated cubic case either: because of the kind of curve we're starting with, we know there is at most a single root in the interval [0,1], simplifying the code we need!

The fact that roots outside the interval [0,1] was assumed, but it's good to make it explicit.

**Comment by Pomax** [comment]
updated in https://github.com/Pomax/BezierInfo-2/commit/d3851791fd4fadb0670b4478a7f264188333630a
