### ISSUE TITLE
Cubic Curve/Line Intersections Edge Case

### ISSUE THREAD

**Issue by Shkyrockett** [Pomax/BezierInfo-2#49]
Thanks for your awesome resource on Bezier curves!

However I have found a broken edge case with the calculation of intersections of Cubic curves and lines.

When finding the intersection of a horizontal line and a Quadratic Bezier, who's endpoints share a y value and the two nodes also independently share a y value, the result of d in the [roots](https://github.com/Pomax/bezierjs/blob/gh-pages/lib/utils.js#L342) method in utils.js ends up as 0. Causing a, b, and c to result in division by 0, so that the result of the roots method is NAN.

![edgecase](https://cloud.githubusercontent.com/assets/16521931/21907870/44cd834c-d8c6-11e6-9ae7-9d49dc9f529f.png)

It looks like the [roots](https://github.com/Pomax/bezierjs/blob/gh-pages/lib/utils.js#L342) method may need a special case for Cubic roots similar to what is used [earlier](https://github.com/Pomax/bezierjs/blob/gh-pages/lib/utils.js#L323) for Quadratic roots.

This would be related to [bezierjs#7](https://github.com/Pomax/bezierjs/issues/7)

**Comment by Pomax** [comment]
cheers!

**Comment by Pomax** [comment]
Testing the specified coordinates today yields `[0.1893696279013022, 0.8106303720986978]` as roots, so closing this in favour of other issues that highlight the same problem but with different coordinates.
