### ISSUE TITLE
fix curve order lowering

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#5]
Read up on the ideal lowering on http://www.sirver.net/blog/2011/08/23/degree-reduction-of-bezier-curves, and document/implement that

**Comment by smichr** [comment]
Is this why the animation near the text "up and down arrow keys to elevate or lower the curve order." doesn't work when you press the down arrow?

**Comment by Pomax** [comment]
This question assumes I'm familiar with something not working that hasn't been brought to my attention. Raising/lowering should work just fine, but the lowered curve will not be the "ideal" form, just a naive lowered curve.

**Comment by Pomax** [comment]
after two and a half years: section updated.
