### ISSUE TITLE
Use 中点 for western names in ja-JP?

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#66]
@mashabow should we use 中点 for names so that things like 「Pierre Bézier」 are written as 「Pierre・Bézier」? It's a fairly common convention in written material that I'm familiar with and removes the oddities that a western space introduces in a running Japanese text.

**Comment by mashabow** [comment]
No. In Japanese text we don't use 中点 for foreign names, unless they are transcripted with katakana. So both "Pierre Bézier" and "ピエール・ベジエ" are OK, while "Pierre・Bézier" looks awkward.

**Comment by Pomax** [comment]
Fair enough.
