### ISSUE TITLE
See if non-Latin character sets can be made to work with MathJax

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#67]
http://docs.mathjax.org/en/latest/font-support.html suggests this should be possible, but the linked dev tools definitely need some digging into before any fontsets can be generated easily.

This would also have to be absolute minimal subsets, as bundling full JP or CN fonts is not an option due to their large size - subset fonts with only the characters used in the content should ideally be used.

**Comment by mashabow** [comment]
How about MathJax's CommonHTML mode, instead of SVG?

![mathjax](https://cloud.githubusercontent.com/assets/6268183/23259511/ce7485c6-fa10-11e6-87b8-acf1e984434a.png)

**Comment by Pomax** [comment]
As far as MathJax goes that should not make a difference, but an HTML rather than SVG output would complicate the build process: right now latex blocks are converted to separate svg files and the original block replaced with an `<img src="file hash">` tag, but crucially the conversion to SVG gets a shortcut: if the file exists, only the `<img src=...>` bit happens, the latex does not get reconverted and we don't spend 10 minutes every `npm run build` waiting for conversions. Converting to HTML would requite a more complex transclusion system because it would have include the result from file, *and* make sure the syntax is JSX conformant (rewriting `class` to `className`, ensuring void elements are closed, etc). 

According to https://github.com/mathjax/MathJax-dev/issues/22#issuecomment-281928196 there should be system font fallback for unknown text, so I'll have to look at what exactly went wrong when I tried this with some Chinese.

**Comment by Pomax** [comment]
Short and sweet: MathJax was too much effort. So I rewrote the code to use XeLaTeX instead, which is an actual LaTeX interpreter. We're running offline already anyway, might as well tap into all the power it has to offer.
