### ISSUE TITLE
Replace English with Japanese in the LaTeX blocks on ja-JP

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#71]
Using a new LaTeX conversion approach, Japanese in LaTeX is now possible, leading to things like this:

![screenshot 178](https://cloud.githubusercontent.com/assets/177243/23350511/e0673538-fc6f-11e6-89dd-db93e443442d.png)

@mashabow does this look like a thing that would be worth doing for all LaTeX blocks? Will this help Japanese audiences?

**Comment by mashabow** [comment]
Great! It would be very helpful.

**Comment by mashabow** [comment]
For Japanese LaTeX text, why don't we use [IPAex Mincho](http://ipafont.ipa.go.jp/) instead of MS Mincho? It is a popular open source font, and already included in TeX Live (`texmf-dist/fonts/truetype/public/ipaex/ipaexm.ttf`). 

```diff
diff --git a/tools/tex-to-svg.js b/tools/tex-to-svg.js
index b78b38d..9e8c0fe 100644
--- a/tools/tex-to-svg.js
+++ b/tools/tex-to-svg.js
@@ -79,7 +79,7 @@ if (process.env.locale === 'ja-JP') {
   filedata = filedata.concat([
     '\\usepackage{xeCJK}',
     '\\xeCJKsetup{CJKmath=true}',
-    '\\setCJKmainfont{MS Mincho}'
+    '\\setCJKmainfont{ipaexm.ttf}'
   ]);
 }
```

**Comment by Pomax** [comment]
Fonts are fluid - as long as it looks good, a free font (Ume Mincho, IPAex Mincho, etc) is always better than a proprietary one.

**Comment by Pomax** [comment]
Tried an export with IPAex Mincho and it looks perfectly fine. It might be worth doing all the LaTeX blocks that involve English text for the already translated sections in one PR.
