### ISSUE TITLE
Rephrase "weight matrix"?

### ISSUE THREAD

**Issue by mashabow** [Pomax/BezierInfo-2#82]
> We can also represent Bézier as matrix operations, by expressing the Bézier formula as a polynomial basis function, the weight matrix, and the actual coordinates as matrix.

In the first sentence of section 6, it seems the term "weight matrix" means the triangular coefficient matrix; while in other sections (e.g. section 4), "weight" generally means the actual coordinates. It would be confusing.

**Comment by Pomax** [comment]
hmm, that's a good point. Let's rewrite that to "coefficient matrix" (I'll update the en-GB file)

**Comment by Pomax** [comment]
I've rephrased it to:

>We can also represent Bézier as matrix operations, by expressing the Bézier formula as a polynomial basis function and a coefficients matrix, and the actual coordinates as matrix. Let's look at what this means for the cubic curve:

**Comment by mashabow** [comment]
Thank you!
