### ISSUE TITLE
localize wiki links in zh-CN content

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#83]
@thrillerist I just realised that many of the wiki links are still on the `en.wikipedia` domain, and I would imagine that for Chinese readers it would be far easier if those point to the Chinese version of wikipedia (where possible) instead.

If that's true, could we update any links that are currently "en" but have Chinese counterparts on wikipedia in sections 0 through 6?

**Comment by thrillerist** [comment]
ok, I'll update these links later.

**Comment by Pomax** [comment]
this got done =D
