### ISSUE TITLE
improve the build system so that it yields an .html file and loose .js for UI handling

### ISSUE THREAD

**Issue by Pomax** [Pomax/BezierInfo-2#86]
Internally the build system can keep using JSX assembly, but the ultimate final result should just be a clean HTML file (which at presents is projected to be 220kb, or 60kb gzipped) with appropriate code for hooking into the necessary handling JS for things like interactive graphics.

This involves splitting up the JSX files as they exist now into things that are "mostly boilerplate" for the actual section `index.js` files, with separate `content.locale.md` files for section content and a `handler.js` for the binding handling.  Once that work has been completed, the build itself can be improved to yield HTML + JS rather than "a stub HTML page with a React application".

I realise that brings the primer full circle to "ye olden dayen" when it was just HTML with Processing.js but at least now everything gets assembled really nicely with easily controlled build steps. As long as the user gets the smallest possible dataset in as little time as possible, the gains of not serving up a React application will be absolutely worth it.

### sections converted

- [x] abc
- [x] aligning
- [x] arcapproximation
- [x] arclength
- [x] arclengthapprox
- [x] boundingbox
- [x] bsplined
- [x] bsplines
- [x] canonical
- [x] catmullconv
- [x] catmullmoulding
- [x] circles
- [x] circles_cubic
- [x] comments
- [x] components
- [x] control
- [x] curveintersection
- [x] decasteljau
- [x] derivatives
- [x] explanation
- [x] extended
- [x] extremities
- [x] flattening
- [x] graduatedoffset
- [x] inflections
- [x] intersections
- [x] introduction
- [x] matrix
- [x] matrixsplit
- [x] moulding
- [x] offsetting
- [x] pointcurves
- [x] pointvectors
- [x] polybezier
- [x] preface
- [x] projections
- [x] reordering
- [x] shapes
- [x] splitting
- [x] tightbounds
- [x] tracing
- [x] whatis

### steps required

- [x] convert all sections to index.js + handler.js + content.locale.md
- [ ] assemble and export the app as clean HTML
- [ ] assemble and export the section JS as a clean keyed handler object
- [ ] hook the section JS into the HTML content
- [ ] update the live site(s)
- [ ] tag a major release

**Comment by josherich** [comment]
btw, just found locale build failed because the `LOCALE` var in npm scripts should be lowercase

**Comment by Pomax** [comment]
Given that I've been running this build multiple times a day for the past few days that seems a dubious claim; can you be specific about which error occurs where, with a log snippet?

**Comment by josherich** [comment]
the `process.env.locale` reference in `webpack.config.js` is lowercase, `LOCALE=zh-CN` reference in npm scripts is uppercase. As far as I know it should be case-sensitive.

**Comment by Pomax** [comment]
Thanks; looks like this is a cross-platform quirk, I'll change it to uppercase in the code.

**Comment by Pomax** [comment]
master branch updated.

**Comment by Pomax** [comment]
After chats with the `preact` folks, it might be possible to do a straight up "render to string" while keeping the interactive elements on the page by turning them into `preact-custom-element`s, which would allow a straight up HTML delivery for users, with "if you have JS enabled, the graphics will work, otherwise they won't" which will be a much better experience for users.

**Comment by Pomax** [comment]
Disentangling the Graphics object is turning out to be significantly more work than I want it to be, which means I am going about this in the wrong way and need to rethink how I want to turn the markdown content into an actual website.

**Comment by Pomax** [comment]
closing, the current setup works.
