### ISSUE TITLE
Add Bitcoin Address

### ISSUE THREAD

**Issue by dbrgn** [Pomax/BezierInfo-2#92]
Hi

I'd love to buy you a coffee, but I don't want to support PayPal. What about publishing a Bitcoin address for donations?

(If you don't want to have your own wallet you could also accept the payments through [Bitpay](https://bitpay.com/docs/donations), although I'd recommend the decentralized version that you control yourself.)

**Comment by Pomax** [comment]
I have no intention of ever using bitcoin, but I'm happy to take "thanks for the awesome article" without the coffee =)

**Comment by dbrgn** [comment]
In that case thanks, I'm only 1/3 through, but great read so far! :)
